title: Nighthawk Pages
description: "Class of 2028"
owner_name: Yasna Ahmadi
github_username: yasna459
github_repo: "yascoolblog"
baseurl: "/yascoolblog"
future: true
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - README4YML.md

head:
  - "<style>
      /* Body background to soft pink */
      body {
        background-color: #ffeef8; /* pastel pink */
      }

      /* Change heading colors to soft pink */
      h1, h2, h3, h4, h5, h6 {
        color: #ff80bf; /* soft pink */
      }

      /* Change links to bright pink */
      a {
        color: #ff3399; /* bright pink */
      }

      a:hover {
        text-decoration: underline;
      }

      /* Modify footer background and text color */
      .site-footer {
        background-color: #ff80bf; /* soft pink */
        color: white;
      }

      /* Adjust button style */
      .btn {
        color: rgba(255, 255, 255, 0.7);
        background-color: rgba(255, 255, 255, 0.08);
        border: 1px solid rgba(255, 255, 255, 0.2);
      }

      .btn:hover {
        background-color: rgba(255, 255, 255, 0.2);
        border-color: rgba(255, 255, 255, 0.3);
      }

      /* Page header to be pink */
      .page-header {
        background-color: #ff80bf; /* soft pink */
        color: white;
        text-align: center;
      }
    </style>"
