title: Yasna's Page
description: "Class of 2028"
owner_name: Yasna Ahmadi
github_username: yasna459
github_repo: "yascoolblog"
baseurl: "/yascoolblog"
future: true
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/game.md
  - navigation/gamify/ChronoCrash.md
  

head:
  - "<link rel='stylesheet' href='/_sass/jekyll-theme-cayman.scss'>"
